// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCu3qLaPTfiJKcqK3cj6faacBb2Mj20y0',
    appId: '1:435019707457:web:7dda5d12066db0b89a82c0',
    messagingSenderId: '435019707457',
    projectId: 'smart-track-81361',
    authDomain: 'smart-track-81361.firebaseapp.com',
    storageBucket: 'smart-track-81361.appspot.com',
    measurementId: 'G-7E0PW7C6RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwp3v57WfOWW4pnDWUQ9z9oplZ-jKKzcU',
    appId: '1:435019707457:android:81445499a687041f9a82c0',
    messagingSenderId: '435019707457',
    projectId: 'smart-track-81361',
    storageBucket: 'smart-track-81361.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPfCFIS0tQnU-BFJtdWccvhPCbrnJjWzU',
    appId: '1:435019707457:ios:ab5e356cf5c8ef8d9a82c0',
    messagingSenderId: '435019707457',
    projectId: 'smart-track-81361',
    storageBucket: 'smart-track-81361.appspot.com',
    iosBundleId: 'com.example.smartTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPfCFIS0tQnU-BFJtdWccvhPCbrnJjWzU',
    appId: '1:435019707457:ios:ab5e356cf5c8ef8d9a82c0',
    messagingSenderId: '435019707457',
    projectId: 'smart-track-81361',
    storageBucket: 'smart-track-81361.appspot.com',
    iosBundleId: 'com.example.smartTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCu3qLaPTfiJKcqK3cj6faacBb2Mj20y0',
    appId: '1:435019707457:web:cbeeddaa9e8bcf959a82c0',
    messagingSenderId: '435019707457',
    projectId: 'smart-track-81361',
    authDomain: 'smart-track-81361.firebaseapp.com',
    storageBucket: 'smart-track-81361.appspot.com',
    measurementId: 'G-MVTLRKMPMG',
  );
}
